# food.py
# Full dataset: 300 realistic African + Middle Eastern foods
# Columns: Food, Category, Calories (kcal/100g), Anti_Inflam (1-10), Notes, Region

import pandas as pd

foods = [
    # --------------------- Nigeria (40) ---------------------
    ("Akamu / Ogi (fermented maize porridge)", "Carbohydrates", 68, 8, "Fermented porridge supports gut health and reduces inflammation", "Nigeria"),
    ("Akara (steamed/baked bean cake)", "Proteins", 206, 8, "Made from black-eyed peas — fiber and plant protein reduce inflammation", "Nigeria"),
    ("Amala (yam or cassava flour swallow)", "Carbohydrates", 330, 7, "Yam/cassava based; choose unprocessed for lower inflammatory load", "Nigeria"),
    ("Banga soup (palm fruit stew)", "Soups/Stews", 250, 7, "Red palm fruit provides carotenoids and tocotrienols with anti-inflammatory properties", "Nigeria"),
    ("Coconut (flesh)", "Fats & Oils", 354, 8, "Contains medium-chain triglycerides which can be less pro-inflammatory", "Nigeria"),
    ("Egusi (melon seed stew)", "Proteins/Fats", 594, 8, "Seeds supply healthy fats, protein and antioxidants", "Nigeria"),
    ("Efo riro (spinach stew)", "Vegetables", 75, 10, "Leafy greens high in polyphenols and vitamins", "Nigeria"),
    ("Ewedu (jute leaves soup)", "Vegetables", 30, 10, "Jute leaves rich in antioxidants and mucilage for gut health", "Nigeria"),
    ("Fufu (cassava or yam)", "Carbohydrates", 160, 7, "Traditional swallow; use pure cassava/yam to avoid wheat fillers", "Nigeria"),
    ("Gbegiri (stewed bean soup)", "Proteins", 120, 9, "Beans are anti-inflammatory when boiled and served without excess oil", "Nigeria"),
    ("Goat meat (grilled/boiled)", "Proteins", 143, 8, "Lean red meat; choose lean cuts and grilling to limit inflammation", "Nigeria"),
    ("Guava", "Fruits", 68, 9, "Vitamin C and polyphenols reduce oxidative stress", "Nigeria"),
    ("Groundnuts (unsalted, roasted)", "Nuts & Seeds", 567, 7, "Healthy fats and antioxidants in moderation", "Nigeria"),
    ("Iru / Dawadawa (fermented locust bean)", "Condiment", 341, 8, "Fermented condiment with bioactives that can support gut health", "Nigeria"),
    ("Lemon (or lime)", "Fruits", 29, 10, "Vitamin C and flavonoids; anti-inflammatory", "Nigeria"),
    ("Mango (moderate)", "Fruits", 60, 8, "Rich in antioxidants but moderate sugar", "Nigeria"),
    ("Moi Moi (steamed bean pudding)", "Proteins", 160, 9, "Steamed legumes preserve anti-inflammatory nutrients", "Nigeria"),
    ("Ogbono (wild mango seed soup)", "Soups/Stews", 190, 8, "Seeds provide healthy fats and mucilage, good for digestion", "Nigeria"),
    ("Ofada rice (unpolished local rice)", "Carbohydrates", 215, 8, "Less processed rice with more fiber and micronutrients", "Nigeria"),
    ("Okra (stew/soup)", "Vegetables", 33, 10, "Mucilage and antioxidants support gut health", "Nigeria"),
    ("Oha soup (oha leaves)", "Vegetables", 45, 9, "Leaves contain flavonoids and phenolics with anti-inflammatory effects", "Nigeria"),
    ("Palm kernel oil (unrefined, limited)", "Fats & Oils", 884, 7, "Unrefined contains antioxidants but use sparingly", "Nigeria"),
    ("Palm oil (red, unrefined, moderate)", "Fats & Oils", 884, 8, "Red palm oil contains carotenoids and tocotrienols; use moderate heat", "Nigeria"),
    ("Pineapple", "Fruits", 50, 8, "Bromelain enzyme reduces inflammation", "Nigeria"),
    ("Plantain (boiled)", "Carbohydrates", 122, 8, "High fiber when unripe; resistant starch helps gut microbiome", "Nigeria"),
    ("Plantain porridge", "Carbohydrates", 140, 8, "Comforting, fiber-rich when made with whole ingredients", "Nigeria"),
    ("Porridge (millet-based)", "Carbohydrates", 119, 9, "Millet is gluten-free and supports stable blood sugar", "Nigeria"),
    ("Scent leaf (efirin)", "Herbs", 30, 10, "Aromatic herb with anti-inflammatory phytochemicals", "Nigeria"),
    ("Tiger nuts (ofio)", "Nuts & Seeds", 496, 8, "High fiber alternative snack that supports gut health", "Nigeria"),
    ("Tomato (fresh, moderate)", "Vegetables", 18, 8, "Source of lycopene with antioxidant effects", "Nigeria"),
    ("Turmeric (with black pepper)", "Herbs & Spices", 312, 10, "Curcumin is a strong anti-inflammatory when paired with piperine", "Nigeria"),
    ("Waterleaf", "Vegetables", 20, 10, "Used in soups; nutrient-rich and anti-inflammatory", "Nigeria"),
    ("Yam (boiled/roasted)", "Carbohydrates", 118, 9, "Resistant starch supports gut and lowers systemic inflammation", "Nigeria"),
    ("Yoghurt (plain, unsweetened)", "Dairy/Probiotic", 59, 8, "Probiotics support gut microbiome and may reduce inflammation", "Nigeria"),
    ("Zobo (hibiscus tea)", "Drinks/Teas", 0, 9, "Rich in anthocyanins which have anti-inflammatory properties", "Nigeria"),

    # --------------------- West Africa (50) ---------------------
    ("African baobab powder", "Superfood / Powder", 250, 9, "High vitamin C and polyphenols; antioxidant and anti-inflammatory", "West Africa"),
    ("African eggplant (garden egg)", "Vegetables", 25, 8, "Phytonutrients with antioxidant benefits", "West Africa"),
    ("African yam bean", "Proteins", 341, 8, "Legume with fiber and protein beneficial for inflammation", "West Africa"),
    ("Achi / Acha (fonio)", "Carbohydrates", 110, 9, "Ancient gluten-free grain, high in micronutrients", "West Africa"),
    ("Asaro (yam porridge)", "Carbohydrates", 142, 8, "Comforting dish with antioxidant vegetables", "West Africa"),
    ("Awusa (palm kernel porridge - minimal)", "Carbohydrates", 200, 6, "Traditional; limit refined fats", "West Africa"),
    ("Bitter leaf soup", "Soups/Stews", 50, 9, "Contains compounds that may reduce inflammatory markers", "West Africa"),
    ("Black sesame (tili)", "Nuts & Seeds", 573, 9, "Rich in sesamin with antioxidant properties", "West Africa"),
    ("Breadfruit (African)", "Carbohydrates", 103, 8, "Starchy fruit with fiber and vitamins", "West Africa"),
    ("Bụrọtọ / Egbo (boiled maize snacks)", "Carbohydrates", 120, 7, "Boiled maize is better than fried for inflammation", "West Africa"),
    ("Buka stew (light, vegetable-forward)", "Soups/Stews", 160, 8, "Vegetable-forward stews reduce inflammation when low in oil", "West Africa"),
    ("Cassava chips (baked)", "Carbohydrates", 160, 7, "Baked option is less inflammatory than fried", "West Africa"),
    ("Cassava leaves soup", "Vegetables", 30, 9, "Leafy greens rich in vitamins and antioxidants", "West Africa"),
    ("Cocoa (dark, >70%)", "Fruits/Chocolate", 546, 9, "Flavanols in dark cocoa reduce inflammation", "West Africa"),
    ("Coconut milk (unsweetened)", "Fats & Oils", 230, 8, "Moderate use; provides creamy texture and MCTs", "West Africa"),
    ("Egusi (melon seeds) soup (light oil)", "Proteins/Fats", 594, 8, "Seeds provide healthy fats and antioxidants", "West Africa"),
    ("Fonio salad", "Carbohydrates/Salad", 110, 9, "Gluten-free side, combines well with vegetables", "West Africa"),
    ("Gari (fermented cassava granules)", "Carbohydrates", 370, 7, "Fermented form can be gentler on gut if prepared traditionally", "West Africa"),
    ("Ginger tea (local)", "Drinks/Teas", 2, 10, "Gingerols reduce inflammatory markers", "West Africa"),
    ("Guinea corn (sorghum) porridge", "Carbohydrates", 329, 8, "Sorghum is antioxidant-rich and gluten-free", "West Africa"),
    ("Kola nut (small amounts)", "Beverage ingredient", 250, 6, "Use sparingly; stimulant properties", "West Africa"),
    ("Kunun (millet or sorghum drink)", "Drinks", 60, 7, "Fermented beverage can support digestion", "West Africa"),
    ("Lokoja pepper (scoped spicy soups)", "Condiment", 40, 7, "Moderate spice combined with anti-inflammatory herbs", "West Africa"),
    ("Maize (boiled)", "Carbohydrates", 96, 7, "Simple staple; good when unprocessed", "West Africa"),
    ("Moringa powder (local)", "Superfood / Powder", 250, 10, "Extremely nutrient-dense and anti-inflammatory", "West Africa"),
    ("Ogi (fermented corn porridge)", "Carbohydrates", 68, 8, "Fermentation supports gut microbiome", "West Africa"),
    ("Ogbono (wild mango) mucus soup (moderate oil)", "Soups/Stews", 200, 8, "Seeds provide healthy fats and thickening mucilage", "West Africa"),
    ("Okpa (Bambara cake)", "Proteins", 341, 9, "Bambara groundnut-based — high in protein/fiber", "West Africa"),
    ("Palm fruit (fresh pulp, moderate)", "Fats & Oils", 250, 8, "Rich in carotenoids when unrefined", "West Africa"),
    ("Papaya (pawpaw)", "Fruits", 43, 9, "Papain enzyme and vitamin C reduce inflammation", "West Africa"),
    ("Periwinkle (sea snail)", "Proteins", 90, 9, "Lean shellfish providing micronutrients and protein", "West Africa"),
    ("Rice (brown/local)", "Carbohydrates", 111, 8, "Less processed rice supports stable blood sugar", "West Africa"),
    ("Roasted plantain (grilled)", "Carbohydrates", 122, 8, "Grilling with minimal oil preserves nutrients", "West Africa"),
    ("Smoked fish (lean, minimal salt)", "Proteins", 150, 8, "Omega-3s present but watch for sodium and processing", "West Africa"),
    ("Snake bean (crowder)", "Proteins", 341, 8, "Legume with fiber and plant compounds", "West Africa"),
    ("Snail (boiled/stewed)", "Proteins", 90, 9, "Lean protein source with iron and minerals", "West Africa"),
    ("Stewed tomatoes (low oil)", "Vegetables", 40, 9, "Tomato lycopene with antioxidant benefits", "West Africa"),
    ("Tilapia (grilled)", "Proteins", 206, 10, "Lean fish with omega-3 fatty acids", "West Africa"),
    ("Tigernut milk", "Drinks", 70, 8, "Plant-based milk rich in fiber and nutrients", "West Africa"),
    ("Tomato pepper stew (light)", "Soups/Stews", 80, 8, "Tomato-based sauces with ginger and garlic", "West Africa"),
    ("Watermelon", "Fruits", 30, 8, "Hydrating fruit with antioxidants", "West Africa"),
    ("Yam pottage (light oil)", "Carbohydrates", 150, 8, "Include vegetables to boost anti-inflammatory effect", "West Africa"),

    # --------------------- East Africa (45) ---------------------
    ("Apple (local)", "Fruits", 52, 9, "High fiber and quercetin; reduces inflammation", "East Africa"),
    ("Avocado (East African varieties)", "Fats & Oils", 160, 10, "Monounsaturated fats reduce inflammation", "East Africa"),
    ("Black cardamom (spice)", "Herbs & Spices", 311, 9, "Aromatic spice with antioxidant properties", "East Africa"),
    ("Black-eyed peas (boiled)", "Proteins", 341, 9, "Legume rich in fiber and antioxidants", "East Africa"),
    ("Breadfruit (East African)", "Carbohydrates", 103, 8, "Starchy fruit with fiber", "East Africa"),
    ("Butter beans (lima)", "Proteins", 338, 8, "High-fiber legume supporting gut health", "East Africa"),
    ("Cassava (boiled)", "Carbohydrates", 160, 8, "Staple carb when prepared simply", "East Africa"),
    ("Chapati (wholegrain teff/alternative)", "Carbohydrates", 200, 8, "Use teff or wholegrain flour to avoid gluten", "East Africa"),
    ("Chicken (stewed/grilled)", "Proteins", 239, 9, "Lean protein; prepare with herbs to reduce inflammation", "East Africa"),
    ("Cowpea (ndengu)", "Proteins", 341, 9, "High protein and fiber; anti-inflammatory benefits", "East Africa"),
    ("Dengu (green grams / mung beans)", "Proteins", 347, 9, "Light legume with antioxidants", "East Africa"),
    ("Ethiopian injera (teff)", "Carbohydrates", 200, 9, "Fermented teff bread high in fiber and minerals", "East Africa"),
    ("Fish stew (tilapia/mukene)", "Proteins", 206, 10, "Omega-3 rich fish reduce inflammation", "East Africa"),
    ("Fresh coconut", "Fats & Oils", 354, 8, "Provide MCTs and support satiety", "East Africa"),
    ("Fermented milk (mursik, amasi variations)", "Dairy/Probiotic", 60, 8, "Fermented dairy supports gut microbiome", "East Africa"),
    ("Finger millet (ragi)", "Carbohydrates", 330, 8, "High in calcium and fiber; gluten-free", "East Africa"),
    ("Fruits salad (local mix)", "Fruits", 65, 9, "Mix of antioxidant fruits reduces inflammation", "East Africa"),
    ("Ginger (fresh)", "Herbs & Spices", 80, 10, "Gingerols lower inflammatory markers", "East Africa"),
    ("Greens (sukuma wiki / collard variants)", "Vegetables", 23, 10, "Leafy greens rich in nutrients", "East Africa"),
    ("Green banana (matoke/boiled)", "Carbohydrates", 89, 8, "Resistant starch supports gut health", "East Africa"),
    ("Honey (raw, local)", "Condiment", 304, 7, "Use sparingly; raw honey has antioxidants", "East Africa"),
    ("Jackfruit (local)", "Fruits", 95, 8, "High in fiber and vitamin C", "East Africa"),
    ("Kales (braised)", "Vegetables", 35, 10, "Leafy cruciferous-like greens with antioxidants", "East Africa"),
    ("Kienyeji chicken (free-range)", "Proteins", 215, 9, "Free-range poultry often leaner and less inflammatory", "East Africa"),
    ("Legume stew (mixed beans)", "Proteins", 140, 9, "Variety of legumes give broad anti-inflammatory benefits", "East Africa"),
    ("Lemon grass tea", "Drinks/Teas", 1, 8, "Citrus-scented tea with calming phytochemicals", "East Africa"),
    ("Mango (local)", "Fruits", 60, 8, "Antioxidant rich but moderate in sugar", "East Africa"),
    ("Millet porridge (uji)", "Carbohydrates", 119, 8, "Fermented millet porridge supports gut health", "East Africa"),
    ("Moringa leaves (fresh or powder)", "Superfood / Veg", 64, 10, "Very high in vitamins and polyphenols", "East Africa"),
    ("Mutton (lean, boiled/grilled)", "Proteins", 250, 7, "Lean cuts preferred; moderate portions", "East Africa"),
    ("Nyama choma (grilled meat, lean cuts)", "Proteins", 250, 7, "Grill lean cuts, avoid char and excess oil", "East Africa"),
    ("Okra (stew)", "Vegetables", 33, 9, "Mucilage supports digestion", "East Africa"),
    ("Papaya", "Fruits", 43, 9, "Papain enzyme aids digestion and inflammation", "East Africa"),
    ("Pineapple", "Fruits", 50, 8, "Bromelain reduces swelling", "East Africa"),
    ("Pumpkin (roasted)", "Vegetables", 26, 9, "Carotenoids with anti-inflammatory potential", "East Africa"),
    ("Sourdough / fermented breads (local)", "Carbohydrates", 250, 8, "Fermentation reduces FODMAPs and improves tolerance", "East Africa"),
    ("Soy (fermented tempeh-style local)", "Proteins", 190, 8, "Fermented soy may be less inflammatory and protein-rich", "East Africa"),
    ("Sweet potato", "Carbohydrates", 86, 9, "Beta-carotene-rich and anti-inflammatory", "East Africa"),
    ("Tamarind (used sparingly)", "Condiment", 239, 7, "Contains antioxidants but tart; use sparingly", "East Africa"),
    ("Teff (whole grain)", "Carbohydrates", 101, 9, "High iron, calcium and fiber; gluten-free", "East Africa"),
    ("Tilapia (smoked/grilled responsibly)", "Proteins", 206, 10, "Lean source of omega-3s when not overly processed", "East Africa"),
    ("Turmeric (local)", "Herbs & Spices", 312, 10, "Curcumin provides strong anti-inflammatory effects", "East Africa"),

    # --------------------- North Africa (40) ---------------------
    ("Almonds", "Nuts & Seeds", 576, 9, "Vitamin E and healthy fats reduce inflammation", "North Africa"),
    ("Apricot (dried or fresh)", "Fruits", 48, 8, "Rich in vitamins and antioxidants", "North Africa"),
    ("Barley (whole)", "Carbohydrates", 354, 9, "Beta-glucans and fiber support gut health", "North Africa"),
    ("Chia seeds", "Nuts & Seeds", 486, 10, "Omega-3-rich seeds with anti-inflammatory effects", "North Africa"),
    ("Chickpeas (boiled/hummus)", "Proteins", 364, 9, "Legumes with fiber and plant protein", "North Africa"),
    ("Cinnamon (ground)", "Herbs & Spices", 247, 9, "Cinnamaldehyde has antioxidant and anti-inflammatory properties", "North Africa"),
    ("Citrus salad (orange/lemon)", "Fruits", 47, 9, "High vitamin C, supports antioxidant defenses", "North Africa"),
    ("Couscous (wholegrain/quinoa alternative)", "Carbohydrates", 112, 8, "Use wholegrain or gluten-free substitutes", "North Africa"),
    ("Ezekiel-style flatbread (local)", "Carbohydrates", 250, 8, "Sprouted grains more digestible and less inflammatory", "North Africa"),
    ("Fava beans (ful)", "Proteins", 341, 9, "Rich in fiber and antioxidants", "North Africa"),
    ("Fresh herbs mix (mint, parsley)", "Herbs", 30, 10, "High in polyphenols and anti-inflammatory compounds", "North Africa"),
    ("Freekeh (green roasted wheat alternative)", "Carbohydrates", 110, 8, "High in fiber and minerals; choose gluten-free when needed", "North Africa"),
    ("Garlic (raw/roasted)", "Herbs & Spices", 149, 10, "Allicin reduces inflammation and supports immune health", "North Africa"),
    ("Ginger (tea or fresh)", "Herbs & Spices", 80, 10, "Gingerols reduce inflammatory cytokines", "North Africa"),
    ("Green tea (Moroccan style)", "Drinks/Teas", 1, 9, "Catechins with antioxidant and anti-inflammatory benefits", "North Africa"),
    ("Hummus (olive oil + chickpeas)", "Proteins", 166, 9, "Combined healthy fats and legumes reduce inflammation", "North Africa"),
    ("Kale (Steamed)", "Vegetables", 35, 10, "Cruciferous-like green with phytonutrients", "North Africa"),
    ("Labneh (strained yogurt)", "Dairy/Probiotic", 97, 8, "Probiotics can modulate inflammation", "North Africa"),
    ("Lentils (stew/soup)", "Proteins", 116, 9, "High fiber legume with anti-inflammatory benefits", "North Africa"),
    ("Lemon juice (fresh)", "Condiment", 29, 10, "Boosts antioxidant intake and flavor without sugar", "North Africa"),
    ("Medjool dates (moderate)", "Fruits", 282, 7, "Natural sugars with antioxidants; moderate portions", "North Africa"),
    ("Morrocan preserved lemon (small amounts)", "Condiment", 40, 7, "Used sparingly for flavor; provides antioxidants", "North Africa"),
    ("Olive oil (extra virgin)", "Fats & Oils", 884, 10, "Mainstay anti-inflammatory oil rich in polyphenols", "North Africa"),
    ("Olives (whole)", "Fats & Oils", 115, 9, "Monounsaturated fats and polyphenols", "North Africa"),
    ("Pomegranate (fresh)", "Fruits", 83, 10, "High polyphenol content reduces inflammatory markers", "North Africa"),
    ("Quinoa salad (North African style)", "Carbohydrates/Salad", 120, 9, "Gluten-free grain mixed with herbs and olive oil", "North Africa"),
    ("Roasted vegetables (eggplant, zucchini)", "Vegetables", 35, 9, "High in fiber and antioxidants when roasted with olive oil", "North Africa"),
    ("Sardines (grilled)", "Proteins", 208, 10, "Excellent source of omega-3s", "North Africa"),
    ("Sea bream / seabass (grilled)", "Proteins", 124, 10, "Lean fish with anti-inflammatory fats", "North Africa"),
    ("Sesame tahini (moderate)", "Fats & Oils", 595, 9, "Sesame lignans and healthy fats", "North Africa"),
    ("Spinach (steamed)", "Vegetables", 23, 10, "Rich in vitamins and polyphenols", "North Africa"),
    ("Sumac (spice)", "Herbs & Spices", 368, 9, "High antioxidant spice used in salads", "North Africa"),
    ("Tomato salad (with olive oil)", "Vegetables", 18, 9, "Lycopene plus olive oil increases antioxidant absorption", "North Africa"),
    ("Turmeric (used in dishes)", "Herbs & Spices", 312, 10, "Curcumin reduces inflammatory pathways", "North Africa"),
    ("Walnuts (small portions)", "Nuts & Seeds", 654, 9, "Rich in ALA omega-3s lowering inflammation", "North Africa"),
    ("Za'atar (herb mix)", "Herbs & Spices", 300, 9, "Oregano/thyme/thyme-like herbs high in antioxidants", "North Africa"),
    ("Zucchini (grilled)", "Vegetables", 17, 9, "Low-calorie vegetable with antioxidants", "North Africa"),

    # --------------------- Central Africa (40) ---------------------
    ("African pear / bush pear (moderate)", "Fruits", 160, 8, "Local fruit with fiber and antioxidants", "Central Africa"),
    ("Beef (lean cuts, grilled/boiled)", "Proteins", 250, 7, "Choose lean cuts and moderate portions", "Central Africa"),
    ("Bitterleaf (soup)", "Vegetables", 45, 9, "Bitter phytochemicals can modulate inflammation", "Central Africa"),
    ("Cassava (boiled)", "Carbohydrates", 160, 8, "Staple root; prepare without excessive frying", "Central Africa"),
    ("Crayfish (dried, used as seasoning)", "Proteins/Seasoning", 67, 8, "Adds flavor with protein and minerals", "Central Africa"),
    ("Egusi seeds (melon)", "Proteins & Fats", 594, 8, "Seed fats and proteins supportive in moderation", "Central Africa"),
    ("Fish (smoked/grilled, local species)", "Proteins", 200, 9, "Opt for fresh or lightly processed fish", "Central Africa"),
    ("Garden egg leaves", "Vegetables", 18, 9, "Leafy green with micronutrients", "Central Africa"),
    ("Gnetum africanum (eru, okok)", "Vegetables", 50, 10, "Leafy green rich in micronutrients and antioxidants", "Central Africa"),
    ("Groundnuts (roasted)", "Nuts & Seeds", 567, 7, "Moderate portions provide healthy unsaturated fats", "Central Africa"),
    ("Jackfruit (local)", "Fruits", 95, 8, "Fibre-rich fruit with vitamins", "Central Africa"),
    ("Koki beans (steamed)", "Proteins", 341, 9, "Steamed bean-based dish high in fiber", "Central Africa"),
    ("Mango (local)", "Fruits", 60, 8, "Antioxidant-rich fruit", "Central Africa"),
    ("Moringa leaves (local)", "Superfood / Veg", 247, 10, "Extremely nutrient dense and anti-inflammatory", "Central Africa"),
    ("Mutton (lean, boiled)", "Proteins", 250, 7, "Lean red meat in moderation", "Central Africa"),
    ("Nsala-style fish pepper soup (light)", "Soups", 120, 9, "Spiced fish soup with ginger and anti-inflammatory aromatics", "Central Africa"),
    ("Okra (local soups)", "Vegetables", 33, 9, "Mucilaginous vegetables benefit gut lining", "Central Africa"),
    ("Palm oil (red, unrefined, limited)", "Fats & Oils", 884, 8, "Unrefined contains carotenoids; use sparingly", "Central Africa"),
    ("Periwinkle (snail)", "Proteins", 90, 9, "Lean protein with low inflammatory profile", "Central Africa"),
    ("Plantain (boiled)", "Carbohydrates", 122, 8, "High in fiber when unripe", "Central Africa"),
    ("Pumpkin (local)", "Vegetables", 26, 9, "Rich in carotenoids and fiber", "Central Africa"),
    ("Rice (local brown varieties)", "Carbohydrates", 111, 8, "Choose unpolished varieties to retain fiber", "Central Africa"),
    ("Smoked tilapia (moderate salt)", "Proteins", 206, 9, "Good omega-3 source if sodium is controlled", "Central Africa"),
    ("Snails (stewed)", "Proteins", 90, 9, "Lean protein with micronutrients", "Central Africa"),
    ("Sorghum (porridge)", "Carbohydrates", 329, 8, "High in antioxidants and fiber", "Central Africa"),
    ("Spinach (traditional)", "Vegetables", 23, 10, "Leafy green packed with anti-inflammatory nutrients", "Central Africa"),
    ("Sweet potato (boiled)", "Carbohydrates", 86, 9, "Beta-carotene and fiber reduce inflammation", "Central Africa"),
    ("Tiger nut (snack/milk)", "Nuts & Seeds", 496, 8, "Rich in fiber and resistant starch", "Central Africa"),
    ("Tomato (local stews)", "Vegetables", 18, 8, "Lycopene-rich when cooked with olive or nut oil", "Central Africa"),
    ("Ugbogoro (fermented locust bean use)", "Condiment", 341, 8, "Fermented seasonings offer gut-friendly compounds", "Central Africa"),
    ("Vegetable stew (leafy greens base)", "Soups/Stews", 90, 9, "High in vitamins and low in pro-inflammatory fats", "Central Africa"),
    ("Waterleaf (soup)", "Vegetables", 20, 10, "High antioxidant content", "Central Africa"),
    ("Wild mushrooms (local varieties)", "Proteins/Vegetables", 22, 9, "Contain antioxidants and immune-modulating compounds", "Central Africa"),
    ("Yam (boiled/roasted)", "Carbohydrates", 118, 9, "Resistant starch supports healthy gut microbiome", "Central Africa"),
    ("Yam pottage (light)", "Carbohydrates", 142, 8, "Include many vegetables to boost anti-inflammatory properties", "Central Africa"),
    ("Yellow maize (boiled)", "Carbohydrates", 96, 7, "Whole-grain maize supports steady blood sugar", "Central Africa"),
    ("Zobo mix (hibiscus blends)", "Drinks/Teas", 1, 9, "Anthocyanin-rich herbal drink reduces inflammation", "Central Africa"),

    # --------------------- Southern Africa (45) ---------------------
    ("Amadumbe (taro) boiled", "Carbohydrates", 142, 8, "Starchy root with fiber and micronutrients", "Southern Africa"),
    ("Avocado (local)", "Fats & Oils", 160, 10, "Healthy monounsaturated fats reduce inflammation", "Southern Africa"),
    ("Biltong (lean dried meat, minimal spice)", "Proteins", 250, 7, "Lean preserved meat in moderation", "Southern Africa"),
    ("Bok choy / local greens", "Vegetables", 13, 10, "Leafy vegetables high in nutrients", "Southern Africa"),
    ("Butternut pumpkin (roasted)", "Vegetables", 45, 9, "Carotenoid-rich and fiber-dense", "Southern Africa"),
    ("Cabbage (steamed)", "Vegetables", 25, 9, "Cruciferous-like benefits when steamed", "Southern Africa"),
    ("Chakalaka (veggie relish, light oil)", "Vegetables", 50, 8, "Vegetable relish strong in spices and antioxidants", "Southern Africa"),
    ("Chia seed porridge", "Nuts & Seeds", 486, 10, "Omega-3-rich seeds supporting anti-inflammation", "Southern Africa"),
    ("Chickpea stews (local)", "Proteins", 364, 9, "Legume-based dishes reduce systemic inflammation", "Southern Africa"),
    ("Chicken (free-range grilled)", "Proteins", 239, 9, "Free-range lean protein option", "Southern Africa"),
    ("Couscous (maize alternative)", "Carbohydrates", 120, 8, "Use wholegrain variations to reduce inflammatory potential", "Southern Africa"),
    ("Cranberry-like berries (local)", "Fruits", 46, 9, "Antioxidant-rich berries with anti-inflammatory effects", "Southern Africa"),
    ("Cucumber (fresh)", "Vegetables", 16, 8, "Hydrating vegetable with minor antioxidants", "Southern Africa"),
    ("Fish (kingklip / local whitefish)", "Proteins", 120, 10, "Lean fish with beneficial fatty acids", "Southern Africa"),
    ("Gooseberry (amla-style local)", "Fruits", 44, 9, "High vitamin C and polyphenols", "Southern Africa"),
    ("Ginger (tea/fresh)", "Herbs & Spices", 80, 10, "Reduces inflammatory mediators", "Southern Africa"),
    ("Honeybush / Rooibos (herbal teas)", "Drinks/Teas", 2, 8, "Rich in antioxidants and calming polyphenols", "Southern Africa"),
    ("Kale (braised)", "Vegetables", 35, 10, "Nutrient-dense leafy green", "Southern Africa"),
    ("Maize meal (samp/samp porridge, minimal processing)", "Carbohydrates", 365, 8, "Choose less processed forms to lower inflammation", "Southern Africa"),
    ("Mackerel (grilled)", "Proteins", 205, 10, "High in omega-3 fatty acids", "Southern Africa"),
    ("Mango (local)", "Fruits", 60, 8, "Antioxidant-rich when consumed in moderation", "Southern Africa"),
    ("Milk (fermented / maas)", "Dairy/Probiotic", 42, 8, "Fermented dairy supports gut bacteria", "Southern Africa"),
    ("Millet (porridge/pap)", "Carbohydrates", 119, 8, "Gluten-free grain with fiber", "Southern Africa"),
    ("Moringa (leaf powder)", "Superfood / Veg", 247, 10, "Dense in vitamins and anti-inflammatory compounds", "Southern Africa"),
    ("Oats (gluten-free)", "Carbohydrates", 389, 8, "Beta-glucans and fiber support gut health", "Southern Africa"),
    ("Olive oil (used sparingly)", "Fats & Oils", 884, 10, "Anti-inflammatory monounsaturated fats", "Southern Africa"),
    ("Orange (local)", "Fruits", 47, 9, "Vitamin C and flavonoids", "Southern Africa"),
    ("Pap (fermented maize porridge)", "Carbohydrates", 68, 8, "Fermented porridges can improve gut health", "Southern Africa"),
    ("Peri-peri (chili) roasted vegetables (light)", "Condiment/Dish", 40, 7, "Use moderate spice; combined with herbs can be anti-inflammatory", "Southern Africa"),
    ("Pineapple", "Fruits", 50, 8, "Bromelain content aids inflammation", "Southern Africa"),
    ("Pistachios (small portions)", "Nuts & Seeds", 562, 9, "Monounsaturated fats and antioxidants", "Southern Africa"),
    ("Pumpkin seeds", "Nuts & Seeds", 559, 9, "Rich in omega-3 and minerals", "Southern Africa"),
    ("Quinoa (as imported / used locally)", "Carbohydrates", 120, 9, "Gluten-free, high protein and fiber", "Southern Africa"),
    ("Roasted root medley (beet, carrot)", "Vegetables", 50, 9, "Roasting with olive oil preserves nutrients", "Southern Africa"),
    ("Sardines (tinned in water or grilled)", "Proteins", 208, 10, "Good omega-3 profile", "Southern Africa"),
    ("Seafood stew (mixed, light broth)", "Proteins", 120, 9, "Lean seafood with herbs reduces inflammation", "Southern Africa"),
    ("Spinach (fresh)", "Vegetables", 23, 10, "High in antioxidants and vitamins", "Southern Africa"),
    ("Sweet potato (boiled)", "Carbohydrates", 86, 9, "Beta-carotene and fiber support reduced inflammation", "Southern Africa"),
    ("Tomato salsa (olive oil)", "Vegetables/Condiment", 18, 9, "Lycopene and healthy fat improve antioxidant absorption", "Southern Africa"),
    ("Tuna (fresh grilled)", "Proteins", 132, 10, "Lean fish with omega-3s when grilled", "Southern Africa"),
    ("Watermelon", "Fruits", 30, 8, "Hydrating fruit with antioxidants", "Southern Africa"),
    ("Wholegrain breads (sourdough-style)", "Carbohydrates", 250, 8, "Sourdough lowers inflammatory response in some people", "Southern Africa"),

    # --------------------- Middle East (40) ---------------------
    ("Adas (lentil soup)", "Proteins", 110, 9, "Lentils provide soluble fiber and anti-inflammatory effects", "Middle East"),
    ("Arabic coffee (light, no sugar)", "Drinks", 2, 6, "Moderate consumption; bitter compounds with antioxidant activity", "Middle East"),
    ("Baklava (small, occasional)", "Dessert", 450, 3, "High sugar and fat — limit for inflammation", "Middle East"),
    ("Baba ganoush (eggplant dip)", "Vegetables/Condiment", 120, 9, "Eggplant and olive oil provide antioxidants", "Middle East"),
    ("Barley porridge (balila)", "Carbohydrates", 354, 9, "Barley fiber supports gut and reduces inflammation", "Middle East"),
    ("Bulgur wheat salad (tabbouleh variant)", "Carbohydrates/Salad", 83, 8, "Herb-forward salad with mint and parsley", "Middle East"),
    ("Dates (Medjool, moderate)", "Fruits", 282, 7, "Natural sugars with antioxidants — moderate portions", "Middle East"),
    ("Figs (fresh)", "Fruits", 74, 8, "Antioxidants reduce oxidative stress", "Middle East"),
    ("Freekeh (roasted green wheat)", "Carbohydrates", 110, 8, "High fiber, low glycemic index", "Middle East"),
    ("Ful medames (fava bean stew)", "Proteins", 341, 9, "High fiber and plant protein, often with olive oil", "Middle East"),
    ("Grilled fish (Levantine style)", "Proteins", 130, 10, "Lean fish with healthy fats and herbs", "Middle East"),
    ("Halloumi (moderate)", "Proteins/Dairy", 321, 6, "Use in moderation; choose low-salt options", "Middle East"),
    ("Herbed labneh (strained yoghurt)", "Dairy/Probiotic", 97, 8, "Probiotic-rich, less inflammatory than processed dairy", "Middle East"),
    ("Hummus (classic)", "Proteins", 166, 9, "Chickpeas + olive oil provides fiber and healthy fats", "Middle East"),
    ("Kebabs (lean grilled meat)", "Proteins", 220, 8, "Grilled lean meats with herbs when not charred", "Middle East"),
    ("Lentil salad", "Proteins/Salad", 116, 9, "Legumes plus herbs and lemon lower inflammation", "Middle East"),
    ("Masticha / herbal teas (unsweetened)", "Drinks/Teas", 0, 8, "Herbal infusions with calming phytochemicals", "Middle East"),
    ("Miso-style fermented flavors (rare local variants)", "Condiment", 40, 8, "Fermented umami components support gut health", "Middle East"),
    ("Mint tea (fresh)", "Drinks/Teas", 1, 8, "Soothing and modest anti-inflammatory benefits", "Middle East"),
    ("Olive oil (extra virgin, kalt gepresst)", "Fats & Oils", 884, 10, "Core Mediterranean anti-inflammatory fat", "Middle East"),
    ("Olive tapenade (moderate)", "Condiment", 200, 8, "Olives and capers with anti-inflammatory olive oil", "Middle East"),
    ("Pistachios (small portions)", "Nuts & Seeds", 562, 9, "Healthy fats and antioxidants", "Middle East"),
    ("Pomegranate molasses (small use)", "Condiment", 260, 9, "Concentrated polyphenols — use sparingly", "Middle East"),
    ("Pomegranate (whole)", "Fruits", 83, 10, "High polyphenol content with anti-inflammatory effects", "Middle East"),
    ("Quinoa pilaf (adopted)", "Carbohydrates", 120, 9, "Gluten-free alternative adopted in the region", "Middle East"),
    ("Sambousek (baked, veggie)", "Snacks", 220, 7, "Baked versions with vegetables are less inflammatory", "Middle East"),
    ("Sardines (Levantine, grilled)", "Proteins", 208, 10, "Excellent omega-3 source", "Middle East"),
    ("Shakshuka (poached eggs in tomato sauce)", "Proteins/Vegetables", 120, 9, "Tomatoes and eggs with olive oil offer balanced nutrition", "Middle East"),
    ("Sumac (spice)", "Herbs & Spices", 368, 9, "High antioxidant spice used on salads and meats", "Middle East"),
    ("Tahini (sesame paste)", "Fats & Oils", 595, 9, "Sesame lignans and healthy fats", "Middle East"),
    ("Tabbouleh (parsley salad)", "Salad", 120, 10, "Parsley, mint, tomato and lemon with olive oil — very anti-inflammatory", "Middle East"),
    ("Tamarind (used moderately)", "Condiment", 239, 7, "Tart flavoring with antioxidants", "Middle East"),
    ("Teff-based breads (adopted)", "Carbohydrates", 101, 9, "Gluten-free teff used increasingly as healthy bread", "Middle East"),
    ("Turmeric (used in stews)", "Herbs & Spices", 312, 10, "Curcumin reduces pro-inflammatory signalling", "Middle East"),
    ("Walnuts (small portions)", "Nuts & Seeds", 654, 9, "High in ALA omega-3s — anti-inflammatory", "Middle East"),
    ("Yoghurt (labneh/plain)", "Dairy/Probiotic", 59, 8, "Probiotic benefits help modulate inflammation", "Middle East"),
    ("Za'atar (thyme/oregano blend)", "Herbs & Spices", 300, 9, "Herb mix rich in antioxidant compounds", "Middle East"),
    ("Zaatar flatbread (light, wholegrain)", "Carbohydrates", 250, 8, "Wholegrain base with herb topping for added antioxidants", "Middle East"),
]

# Convert to DataFrame and sort alphabetically by Food name
df = pd.DataFrame(foods, columns=["Food", "Category", "Calories", "Anti_Inflam", "Notes", "Region"])
df = df.sort_values(by="Food").reset_index(drop=True)
